### ISSUE TITLE
ACI Module. iPV6 routing issue

### ISSUE THREAD

**Issue by rajeshagadi** [Microsoft/MTC_ContainerCamp#32] opened 2017-10-28 00:50 UTC
In the ACI Module:  Task 1: Create ASP.NET Core Hello World Application

The line .UseUrls("http://*:8080") translates in to  hosting the app on browser with url http://[::]:8080.

In my Win 2016 server (using as my docker dev  (Refer my rant on team re:docker)), the IE Browse fails to resolve. 

![image](https://user-images.githubusercontent.com/17166696/32129664-07940814-bb3f-11e7-9b53-25823c77294e.png)

So the ping [::] fails. Then tried https://www.rootusers.com/how-to-enable-ping-in-windows-server-2016-firewall/ (Refer to #3 for iPV6), tried enable fire wall rules, no success.

![image](https://user-images.githubusercontent.com/17166696/32129678-3a96e4f2-bb3f-11e7-8da6-82adcd6d9d8d.png)

So for now I am using http://localhost:8080 which works and I am moving forward. Just keep an eye on this.

**Comment by amazaheri** [comment] 2018-03-16 16:16
Hi @JeffBrand do you have any update on this?

**Comment by amazaheri** [comment] 2018-04-01 02:28
Hi guys any update on this? still happening? should we close?

**Comment by amazaheri** [comment] 2018-04-12 01:55
Could not able to reproduce. Closing.

**Closed by amazaheri** 2018-04-12 01:55 UTC
Labels: bug
